export const LOADING = 'LOADING';
export const GET_LATEST_NEWS = 'GET_LATEST_NEWS';
export const ACTIVE_AUTO_COMPLETE = 'ACTIVE_AUTO_COMPLETE';
export const SEARCH_NEWS = 'SEARCH_NEWS';
export const GET_ERROR = 'GET_ERROR';